#!/usr/bin/env bash
# find-or-create-autofix-pr.sh — reuses an open autofix PR for an issue or creates one.
# Usage: find-or-create-autofix-pr.sh <repo> <issue-num> <branch> <title> <body-file> <GH_TOKEN>
# Outputs (GITHUB_OUTPUT format): pr_number, pr_url, action=created|reused
set -euo pipefail

REPO="$1"
ISSUE_NUM="$2"
BRANCH_NAME="$3"
TITLE="$4"
BODY_FILE="$5"
export GH_TOKEN="$6"

EXISTING_PR=$(gh pr list --repo "$REPO" --head "$BRANCH_NAME" --state open \
  --json number,url --jq ".[0] | {number: .number, url: .url}" 2>/dev/null || echo "null")
PR_NUMBER=$(echo "$EXISTING_PR" | jq -r '.number // empty')
PR_URL=$(echo "$EXISTING_PR" | jq -r '.url // empty')

if [ -n "$PR_NUMBER" ]; then
  [ -f "$BODY_FILE" ] && gh pr edit "$PR_NUMBER" --body-file "$BODY_FILE" --repo "$REPO" 2>/dev/null || true
  echo "pr_number=${PR_NUMBER}"
  echo "pr_url=${PR_URL}"
  echo "action=reused"
else
  BODY="## Fixes #${ISSUE_NUM}

"
  [ -f "$BODY_FILE" ] && BODY="${BODY}$(cat "$BODY_FILE")

"
  BODY="${BODY}---
*Auto-generated by CodeSentinel*"
  PR_URL=$(gh pr create --repo "$REPO" --base main --head "$BRANCH_NAME" --title "$TITLE" --body "$BODY")
  PR_NUMBER=$(echo "$PR_URL" | grep -oP '/pull/\K[0-9]+' || echo "")
  if [ -n "$PR_NUMBER" ]; then
    gh pr edit "$PR_NUMBER" --add-label "autofix" --repo "$REPO" 2>/dev/null || true
  fi
  echo "pr_number=${PR_NUMBER}"
  echo "pr_url=${PR_URL}"
  echo "action=created"
fi